name: Anvil
main: io.github.explosivemine.anvil.AnvilPlugin
version: '${project.version}'
description: Virtual anvil
api-version: 1.17
author: explosivemines
website: https://www.spigotmc.org/resources/anvil.77142/
commands:
  anvil:
    description: Open an anvil anywhere!